# Generated by Django 5.2.12 on 2026-03-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_acessorio_cor_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, default='padrao', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, default='padrao', max_length=80),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('acessorios', models.ManyToManyField(blank=True, to='core.acessorio')),
                ('cor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cor')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modelo')),
            ],
        ),
    ]
